version: 0.0.{build}
skip_tags: true
clone_depth: 1
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
cache: C:\Users\appveyor\.nuget\packages
configuration: Release
before_build:
  - ps: Import-Module .\build\psake.psm1
build_script:
  - ps: Invoke-Psake .\build\build.ps1 -properties @{"Configuration"=$env:CONFIGURATION;"Version"=$env:APPVEYOR_BUILD_VERSION}
test: off
artifacts:
  - path: 'artifacts\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: 4eGPThK/wSpRmfINQgAGQZD/e8r6FKRfp0SN4nB5/FBTHKJ1xIf/BK3/Iz5csDFm
  artifact: /.*\.nupkg/